name: vanillajs Vite App User scenario
author: clara osterburg correa
description: vanillajs test

services:
  project:
    image: project
    build:
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - chrome-headless
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: 1
  gcb-puppeteer:
    image: greencoding/puppeteer-chrome
    volumes:
      - ./puppeteer-flow.js:/var/www/puppeteer-flow.js
    environment:
      # If you have multiple displays please change this to the entry you want under /tmp/X11-unix
      DISPLAY: ":0"
    networks:
      - chrome-headless
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: 1



flow:
  - name: Check Website
    container: gcb-puppeteer
    commands:
      - type: console
        command: node /var/www/puppeteer-flow.js
        note: Starting Puppeteer Flow
        read-notes-stdout: true
        log-stdout: true
        read-sci-stdout: true

networks:
  chrome-headless:
